// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdm5Xmc-sdqgA3Py3Sc5rQOYs5SP_FPww',
    appId: '1:625455130422:web:5c5ca912a717c553b4f597',
    messagingSenderId: '625455130422',
    projectId: 'chickmate-ef0a0',
    authDomain: 'chickmate-ef0a0.firebaseapp.com',
    databaseURL: 'https://chickmate-ef0a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chickmate-ef0a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkj9N0YV4RLwnlZbyT_ZEnfvggjpgtHBg',
    appId: '1:625455130422:android:5a59b41c74f3fad3b4f597',
    messagingSenderId: '625455130422',
    projectId: 'chickmate-ef0a0',
    databaseURL: 'https://chickmate-ef0a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chickmate-ef0a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_XCDeq8xtI0yCkgsOm25wg_Mx_d1zkrE',
    appId: '1:625455130422:ios:16ad664111b81c15b4f597',
    messagingSenderId: '625455130422',
    projectId: 'chickmate-ef0a0',
    databaseURL: 'https://chickmate-ef0a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chickmate-ef0a0.firebasestorage.app',
    iosBundleId: 'com.example.chickmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_XCDeq8xtI0yCkgsOm25wg_Mx_d1zkrE',
    appId: '1:625455130422:ios:16ad664111b81c15b4f597',
    messagingSenderId: '625455130422',
    projectId: 'chickmate-ef0a0',
    databaseURL: 'https://chickmate-ef0a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chickmate-ef0a0.firebasestorage.app',
    iosBundleId: 'com.example.chickmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdm5Xmc-sdqgA3Py3Sc5rQOYs5SP_FPww',
    appId: '1:625455130422:web:e59ddb2673f59b10b4f597',
    messagingSenderId: '625455130422',
    projectId: 'chickmate-ef0a0',
    authDomain: 'chickmate-ef0a0.firebaseapp.com',
    databaseURL: 'https://chickmate-ef0a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chickmate-ef0a0.firebasestorage.app',
  );

}