// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbmnFxfSsiH8AxC3XzAZLaPUOV_6Sk-zk',
    appId: '1:581019756993:web:be9378c7eb3c375157e740',
    messagingSenderId: '581019756993',
    projectId: 'chickmate-60301',
    authDomain: 'chickmate-60301.firebaseapp.com',
    databaseURL: 'https://chickmate-60301-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chickmate-60301.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzMHy_0de5DwTSkbgyefkpqCKrmQCy6YQ',
    appId: '1:581019756993:android:8dcbc8b33247972757e740',
    messagingSenderId: '581019756993',
    projectId: 'chickmate-60301',
    databaseURL: 'https://chickmate-60301-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chickmate-60301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9XoORLjPHahR_uIgS2ayFf5mD_2QgsvE',
    appId: '1:581019756993:ios:3bf1258600dbde7f57e740',
    messagingSenderId: '581019756993',
    projectId: 'chickmate-60301',
    databaseURL: 'https://chickmate-60301-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chickmate-60301.firebasestorage.app',
    iosBundleId: 'com.example.chickmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9XoORLjPHahR_uIgS2ayFf5mD_2QgsvE',
    appId: '1:581019756993:ios:3bf1258600dbde7f57e740',
    messagingSenderId: '581019756993',
    projectId: 'chickmate-60301',
    databaseURL: 'https://chickmate-60301-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chickmate-60301.firebasestorage.app',
    iosBundleId: 'com.example.chickmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbmnFxfSsiH8AxC3XzAZLaPUOV_6Sk-zk',
    appId: '1:581019756993:web:817bf4301d99c25a57e740',
    messagingSenderId: '581019756993',
    projectId: 'chickmate-60301',
    authDomain: 'chickmate-60301.firebaseapp.com',
    databaseURL: 'https://chickmate-60301-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chickmate-60301.firebasestorage.app',
  );
}
